repos:

  - repo: local
    hooks:
      - id: system-ruff
        name: System Ruff Check
        entry: ruff check .
        language: system
        pass_filenames: false
        stages: [pre-commit]

      - id: system-mypy
        name: System Mypy
        entry: mypy splurge_safe_io
        language: system
        pass_filenames: false
        stages: [pre-commit]
        
      - id: system-pytest
        name: System Pytest
        entry: pytest -q
        language: system
        pass_filenames: false
        stages: [pre-commit]
